name: Build CaptiveDNS

on:
  push:
    branches:
      - main
      - ci-release
  pull_request:
    branches:
      - main

jobs:
  all:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@main
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build ${{ matrix.platform }}
      shell: bash
      run: cd CaptiveDNS && qmake
    - uses: actions/upload-artifact@v3
      with:
        name: Makefile.Release
        path: ./CaptiveDNS/Makefile.Release